name: Publish Docker Image to Registry

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          use: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: heyvaldemar/quake3-server:latest, heyvaldemar/quake3-server:${{ github.sha }}
          cache-from: type=registry,ref=heyvaldemar/quake3-server:cache
          cache-to: type=inline
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
